<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="EnvioMQTT" Id="{a99b8f2d-ec49-41f1-8953-0cfffa96d515}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM EnvioMQTT
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EnvioMQTT">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>